# Generated by Django 5.1.6 on 2025-02-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ONLINE_SERVICES', 'Online Services'), ('TRAVEL', 'Travel'), ('FOOD', 'Food'), ('RENT', 'Rent'), ('OTHER', 'Other')], max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
